//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Skills_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalPrescriptions
    {
        public int hospital_prescription_id { get; set; }
        public int patient_id { get; set; }
        public int medical_activites_id { get; set; }
        public string drug_title { get; set; }
    
        public virtual MedicalActivites MedicalActivites { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
