//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Skills_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalisations
    {
        public int hospitalisation_id { get; set; }
        public int patient_id { get; set; }
        public int hospital_id { get; set; }
        public int admission_type_id { get; set; }
        public string hospitalisation_code { get; set; }
        public byte[] hospitalisation_date { get; set; }
        public string purpose { get; set; }
        public string diagnose { get; set; }
    
        public virtual AdmissionTypes AdmissionTypes { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
