//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Skills_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalActivites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalActivites()
        {
            this.HospitalPrescriptions = new HashSet<HospitalPrescriptions>();
        }
    
        public int medical_activites_id { get; set; }
        public int patient_id { get; set; }
        public int doctor_id { get; set; }
        public int medical_type_id { get; set; }
        public System.DateTime holding_date { get; set; }
        public string title { get; set; }
        public string result { get; set; }
        public string recomendation { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalPrescriptions> HospitalPrescriptions { get; set; }
        public virtual MedicalActiveTypes MedicalActiveTypes { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
