//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Skills_Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistories
    {
        public int medical_history_id { get; set; }
        public int medical_card_id { get; set; }
        public string diagnose { get; set; }
    
        public virtual MedicalCards MedicalCards { get; set; }
    }
}
