//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Skills_Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkillsEntities : DbContext
    {
        public WorldSkillsEntities()
            : base("name=WorldSkillsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionTypes> AdmissionTypes { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Hospitalisations> Hospitalisations { get; set; }
        public virtual DbSet<HospitalPrescriptions> HospitalPrescriptions { get; set; }
        public virtual DbSet<Hospitals> Hospitals { get; set; }
        public virtual DbSet<InsurancePoles> InsurancePoles { get; set; }
        public virtual DbSet<MedicalActiveTypes> MedicalActiveTypes { get; set; }
        public virtual DbSet<MedicalActivites> MedicalActivites { get; set; }
        public virtual DbSet<MedicalCards> MedicalCards { get; set; }
        public virtual DbSet<MedicalHistories> MedicalHistories { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
    }
}
